name: NetherReset
author: Schmoller

version: 1.0.1

main: au.com.mineauz.NetherReset.NetherReset

load: postworld

softdepend: [GriefPrevention]

commands:
  resetNether:
    description: Resets the nether
    permission: resetNether.command
    
permissions:
  resetNether.command:
    default: op
  resetNether.no-portal-delay:
    description: Allows a player to use portals without any wait time
    default: op