name: NetherReset
author: Schmoller

version: 1.0

main: au.com.mineauz.NetherReset.NetherReset

load: postworld

softdepend: [GriefPrevention]

commands:
  resetNether:
    description: Resets the nether
    permission: resetNether.command
  tpn:
    
permissions:
  resetNether.command:
    default: op